### PR TITLE
helper scripts for installing and removing all packages

### PR DESCRIPTION
**Pull request by bcruddy**
Install and remove packages for all of MoonMail (main, events, api) with one script instead of having to `cd` in and out of directories to get all dependencies installed.

From the root MoonMail directory:

~~`./install_packages.sh` to install~~
`npm run install-all`
~~`./remove_packages.sh` to remove `node_modules` directories~~
`npm run remove-all` ~~-> just echo's "not implemented"~~

EDIT: swapped shell scripts for npm scripts~~, need to decide how to remove directories cross platform (or omit it from the PR entirely) per @davidgf comment~~.

### CODE REVIEW

**Comment by davidgf** [comment]
@bcruddy, first off, thank you very much for your contribution! Actually, we were considering adding this same functionality, but using npm scripts instead of shell. Would you be willing to do it that way?

**Comment by bcruddy** [comment]
@davidgf definitely. I'm assuming you want to use npm scripts as they don't need to rely on bash being installed. If that's the case, we can't use `rm` to remove directories. The install script is super simple, I'll push that commit now. As far as a remove script goes - would you be open to adding another dependency like [rimraf](https://www.npmjs.com/package/rimraf)? This would require another script to execute but javascript could handle all of it.

**Comment by davidgf** [comment]
Actually, we want to use `npm` because we can avoid creating new files for simple tasks and centralize them all in one place, so feel free to use `rm` for uninstall as well 😄

**Comment by bcruddy** [comment]
@davidgf that makes sense. I think `npm run install-all` is pretty clear but `npm run remove-all` may not be. I'll leave naming conventions up to you but the scripts do their jobs.

**Comment by davidgf** [comment]
`remove-all` will do. Thank you very much for your contribution!

**Pull request merged**
