### PR TITLE
Feature - campaign activity based segments

### PR DESCRIPTION
**Pull request by ccverak**

### CODE REVIEW

**Comment by aspiers** [comment]
This sounds really cool!  Do I understand right that it would let you automatically generate a new segment from the set of users who took a certain action in a campaign, such as clicking through to a particular link, and then create a new campaign targetting that segment?

**Comment by ccverak** [comment]
@aspiers Yes, that's the idea, this pull will add support segmenting subscribers according to their for click/open activity or inactivity in periods of time or range of campaigns.

**Comment by aspiers** [comment]
Sorry if this is a stupid question, but is this feature available on moonmail.io yet, and if so how can it be used?

**Comment by alexandresaiz** [comment]
Hey adam. I’d suggest contacting MoonMail.io support

**Comment by aspiers** [comment]
Thanks @alexandresaiz, I'll do that.

**Pull request merged**
